[2022-05-04 15:05:44,007] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: emission_dag.run_etl manual__2022-05-04T15:04:40.228833+00:00 [queued]>
[2022-05-04 15:05:44,022] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: emission_dag.run_etl manual__2022-05-04T15:04:40.228833+00:00 [queued]>
[2022-05-04 15:05:44,023] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-04 15:05:44,023] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-05-04 15:05:44,023] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-04 15:05:44,039] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_etl> on 2022-05-04 15:04:40.228833+00:00
[2022-05-04 15:05:44,045] {standard_task_runner.py:52} INFO - Started process 5290 to run task
[2022-05-04 15:05:44,048] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'emission_dag', 'run_etl', 'manual__2022-05-04T15:04:40.228833+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/emission-dag.py', '--cfg-path', '/tmp/tmpcnghsoyd', '--error-file', '/tmp/tmpc_1ehyes']
[2022-05-04 15:05:44,049] {standard_task_runner.py:77} INFO - Job 4: Subtask run_etl
[2022-05-04 15:05:44,108] {logging_mixin.py:109} INFO - Running <TaskInstance: emission_dag.run_etl manual__2022-05-04T15:04:40.228833+00:00 [running]> on host 936fa37c1ac0
[2022-05-04 15:05:44,163] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Aniket
AIRFLOW_CTX_DAG_ID=emission_dag
AIRFLOW_CTX_TASK_ID=run_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-05-04T15:04:40.228833+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-04T15:04:40.228833+00:00
[2022-05-04 15:05:44,164] {logging_mixin.py:109} INFO - >>> Running 'extract' function. Logged at 2022-05-04 15:05:44.164700+00:00
[2022-05-04 15:05:44,165] {logging_mixin.py:109} INFO - extracting the data
[2022-05-04 15:05:44,167] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/emission-dag.py", line 74, in final
    df_drivers_raw, df_veh_cons_raw, df_drivers_logbook_raw = extract(drivers, vehicle_fuel_consumptions, drivers_logbook)
  File "/opt/airflow/dags/emission-dag.py", line 39, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/emission-dag.py", line 60, in extract
    df_drivers_raw = pd.read_csv(drivers)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/data/drivers.csv'
[2022-05-04 15:05:44,186] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=emission_dag, task_id=run_etl, execution_date=20220504T150440, start_date=20220504T150544, end_date=20220504T150544
[2022-05-04 15:05:44,202] {standard_task_runner.py:92} ERROR - Failed to execute job 4 for task run_etl
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/emission-dag.py", line 74, in final
    df_drivers_raw, df_veh_cons_raw, df_drivers_logbook_raw = extract(drivers, vehicle_fuel_consumptions, drivers_logbook)
  File "/opt/airflow/dags/emission-dag.py", line 39, in wrapper
    to_execute = func(*args, **kwargs)
  File "/opt/airflow/dags/emission-dag.py", line 60, in extract
    df_drivers_raw = pd.read_csv(drivers)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/data/drivers.csv'
[2022-05-04 15:05:44,221] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-04 15:05:44,274] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
